---
- hosts: samplehost
  user: admuser
  sudo: yes
  tasks:
  - name: Apt install Nginx
    apt:  pkg=nginx state=latest force=yes update_cache=yes
  - name: copy nginx.conf
    copy:
      src: /data/ansible/template/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: copy fontend.conf.sample
    copy:
      src: /data/ansible/template/nginx/conf.d/frontend.conf
      dest: /etc/nginx/conf.d/frontend.conf.sample
  - name: copy backend.conf.sample
    copy:
      src: /data/ansible/template/nginx/conf.d/backend.conf
      dest: /etc/nginx/conf.d/backend.conf.sample
  - name: copy nginx logrotate
    copy:
      src: /data/ansible/template/logrotate/nginx
      dest: /etc/logrotate.d/nginx
      force: yes
  - name: conf.d chown
    file:
      state: directory
      path: /etc/nginx/conf.d
      group: devuser
      owner: devuser
  - name: www-data user add subgroup
    user:
      name: www-data
      groups: devuser
  - name: documentroot chown
    file:
      state: directory
      recurse: yes
      path: /var/www
      group: devuser
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes

