---
- hosts: samplehost
  user: admuser
  sudo: yes
  tasks:
  - name: create sftp-user group
    group:
      name: sftp-user
      state: present
  - name: create sftpuser
    user:
      name: testftp
      group: sftp-user
      state: present
      home: /data/testftp
      shell: /usr/sbin/nologin
  - name: create home directory
    file:
      state: directory
      path: /data/testftp
      mode: 0755
      group: root
      owner: root
  - name: create Upload directory
    file:
      state: directory
      path: /data/testftp/Upload
      mode: 0777
      group: sftp-user
      owner: testftp   
  - name: add sshd.sftp.service
    blockinfile:
      path: /etc/systemd/system/sshd_sftp.service
      create: yes
      block: |
        [Unit]
        Description=OpenSSH server daemon only sftp
        After=syslog.target network.target auditd.service

        [Service]
        EnvironmentFile=/etc/default/ssh
        ExecStart=/usr/sbin/sshd -D -f /etc/ssh/sshd_sftp
        ExecReload=/bin/kill -HUP $MAINPID
        KillMode=process
        Restart=on-failure
        RestartSec=42s

        [Install]
        WantedBy=multi-user.target
  - name: add sshd_sftp.systemd
    systemd:
      name: sshd_sftp.service
      enabled: yes
      state: started
  - name: setting sftp rsyslog2
    replace:
        path: /etc/rsyslog.d/50-default.conf
        backup: yes
        regexp: '^\*.\*;local5'
        replace: '*.*;local4.none;local5'
  - name: setting sftp rsyslog
    blockinfile:
       dest: /etc/rsyslog.d/50-default.conf
       backup: yes
       create: yes
       state: present
       insertafter: '^#user.*'
       block: |
          local5.*                      -/var/log/snoopy.log
          local4.*                      -/var/log/sftp.log
    notify: restart rsyslog
  - name: create sshd_sftp config
    blockinfile:
      path: /etc/ssh/sshd_sftp
      create: yes
      block: |
        Port 22
        Protocol 2
        SyslogFacility AUTHPRIV


        PermitRootLogin no
        PasswordAuthentication no
        ChallengeResponseAuthentication no


        GSSAPIAuthentication yes
        GSSAPICleanupCredentials yes

        UsePAM yes

        AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
        AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
        AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
        AcceptEnv XMODIFIERS

        X11Forwarding yes
        PidFile /var/run/sftp.pid

        # ssh/sftpを利用できるグループを制限。
        AllowGroups sftp-user

        UseDNS no
        GSSAPIAuthentication no

        Subsystem   sftp    internal-sftp -f local4 -l VERBOSE -u 000
        Match user testftp
            ChrootDirectory /data/testftp
            X11Forwarding no
            AllowTcpForwarding no
            PubkeyAuthentication yes
            AuthorizedKeysFile /data/testftp/.ssh/authorized_keys
    notify: restart sshd_sftp
  handlers:
   - name: restart rsyslog
     service: name=rsyslog state=restarted
   - name: restart sshd_sftp
     service: name=sshd_sftp state=restarted
